# Generated by Django 4.0.3 on 2022-04-24 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseCode', models.CharField(default='12345', max_length=9, primary_key=True, serialize=False)),
                ('courseNumber', models.CharField(default='101', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('IDNumber', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=20)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=11)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('sectionCode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('TA', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TAScheduler.myuser')),
                ('parentCode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TAScheduler.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='instructorID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TAScheduler.myuser'),
        ),
        migrations.CreateModel(
            name='ClassTAAssignments',
            fields=[
                ('AssignmentsID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('TAcode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TAScheduler.myuser')),
                ('courseCode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TAScheduler.course')),
            ],
        ),
    ]
