# Generated by Django 4.0.3 on 2022-04-20 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TAScheduler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='id',
        ),
        migrations.RemoveField(
            model_name='ta',
            name='id',
        ),
        migrations.AddField(
            model_name='course',
            name='TAname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TAScheduler.ta'),
        ),
        migrations.AddField(
            model_name='course',
            name='courseCode',
            field=models.CharField(default='12345', max_length=9, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='course',
            name='courseNumber',
            field=models.CharField(default='101', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='instructorID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TAScheduler.myuser'),
        ),
        migrations.AddField(
            model_name='ta',
            name='TACode',
            field=models.CharField(default='42', max_length=20, primary_key=True, serialize=False),
        ),
    ]
