# Generated by Django 4.0.3 on 2022-04-25 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TAScheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='sections',
            name='TA',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TAScheduler.myuser'),
        ),
    ]
