# Generated by Django 4.0.3 on 2022-05-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TAScheduler', '0002_alter_course_coursecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courseCode',
            field=models.CharField(default='12345', max_length=9, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='skills',
            name='SkillDescription',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
